server:
  port: 80
  context-path: /
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_shop
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  velocity:
    cache: false
  groovy:
    template:
      cache: false